version: '4.47.0'
services:
  db:
    image: mysql:latest
    container_name: interesting_zhukovsky
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    container_name: helloworld
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - app
volumes:
  db_data: